### ISSUE TITLE
Chinese,Japanese, Korean characters do not display correctly 

### ISSUE THREAD

**Issue by cheatmo** [Magisk-Modules-Repo/Magisk-ios10-Emoji-font#4]
Hi, I am using HTC10 with venom 5.80 rom
With magisk 12.
After install emoji font, my phone cannot display Chinese, Japanese, Korean...  correctly, after disable all work fine.
Can I do something to fix this? 
Thanks so much!

**Comment by jplwolters** [comment]
I know what the problem is. Will fix this in the next week. Thx for you feedback

**Comment by jplwolters** [comment]
It is fixed in version 5 :)

**Comment by cheatmo** [comment]
Thanks :)
