### ISSUE TITLE
Add Support for HTC

### ISSUE THREAD

**Issue by Kellwa** [Magisk-Modules-Repo/Magisk-ios10-Emoji-font#8]
i have an HTC desire 820 with andriod 6.0.1
to change my emoji font i used to replace tow files in /system/fonts:
hTC_ColorEmoji.ttf
NotoColorEmoji.ttf
which i replace them with same file but different names
but i know nothing about your post_fsdata script and what does it do
**so i hope you can add the support for HTC devices**

**Comment by jplwolters** [comment]
fixed
